- include_vars: vault.yml
  no_log: true

- name: copy ssh secret key
  copy: >
    content="{{ secret_key }}"
    dest=~/.ssh/id_rsa
    mode=0600
  become: yes
  become_user: "{{ operator }}"

- name: ssh-keygen
  command: ssh-keygen -t rsa -y -f ~/.ssh/id_rsa
  become: yes
  become_user: "{{ operator }}"

- name: install git
  apt: name=git state=present

