- name: import public key 
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10

- name: create mongodb sources list
  shell: echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

- name: install mongodb
  apt: name=mongodb-org update_cache=yes state=latest
